[versions]
agp = "8.7.3"
androidMail = "1.6.2"
compiler = "4.15.1"
compilerVersion = "4.16.0"
glide = "4.16.0"
gson = "2.10.1"
jtds = "1.3.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleLivedataKtx = "2.8.7"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
googleGmsGoogleServices = "4.4.2"
firebaseStorage = "21.0.1"
media = "1.7.0"
media3Common = "1.5.1"
palette = "1.0.0"
retrofit = "2.9.0"

[libraries]
android-activation = { module = "com.sun.mail:android-activation", version.ref = "androidMail" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "androidMail" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compiler-v4160 = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jtds = { module = "net.sourceforge.jtds:jtds", version.ref = "jtds" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
media = { module = "androidx.media:media", version.ref = "media" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3Common" }
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

